# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_collections', '0004_collectionitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
